# Generated by Django 5.0.1 on 2024-11-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_userprofileinfo_company_userprofileinfo_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='Email_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
